
export interface Package {
    id: 1,
    packageNumber: 1,
    workName: '',
    tenderAmout: 100,
    resolutionNumber: 123,
    workOrderNumber: 1234,
    contractor: 'testContractor',
    raBillNumber: 122,
    contractAmout: 80,
    updatedWorkValue: 120,
    juniorEnggName: 'testJE',
    juniorEnggEmpCode: 1,
    deputyEnggName: 'testDE',
    deputyEnggEmpCode: 2,
    executiveEnggName: 'testEE',
    executiveEnggEmpCode: 3,
    workType: 1,  // road/riverBridge/Flyover/underpass
    length: '1.2m',
    width: '2.5m',
    consultantName: 'testConsultant',
    consultantWorkOrder: 12,
    consultantStandingCommitteeResolution: 12345,
    consultantRABill: 1234,
    consultantUpdatedWorkValue: 40,
    percentageQuoteConsultant: 5,
    percentageQuoteContractor: 10,
    dateTime: '',
    remarks: ''
}